# Generated by Django 4.0 on 2023-02-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='providers',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='services',
            field=models.ManyToManyField(null=True, related_name='providers', to='services.Service'),
        ),
    ]
